POST http://localhost:5000/api/users/register
Content-Type: application/json
Accept: application/json

{
  "name": "John Doe",
  "email": "john@john.com",
  "password": "123456",
  "passwordConfirmation": "123456"
}
